name: pull-requests
on: pull_request

jobs:
  # This job handles Buf integration. Namely, it provides inline comments
  # for lint issues and breaking changes.
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.24.0"
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/fixie-ai/fixie-proto.git#branch=main"
  # This job adds suggestions for format changes and a Python version increment.
  # Some version increment is necessary for successfully pushing to PyPI, but it's
  # up to developers whether that push should happen.
  format-and-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.24.0"
          github_token: ${{ github.token }}
        # Unlike lint and breaking, format does not make its own suggestions,
        # so we use action-suggester to make them.
      - run: buf format
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: "buf format"

        # TODO(mdepinet): GitHub doesn't allow adding suggestions or comments
        # to unchanged files *or unchanged lines* so unfortunately for now the
        # best we can do is add a generic PR-level comment. :/
      - uses: thollander/actions-comment-pull-request@v2
        with:
          message: "If your change should be published to PyPI, don't forget to bump the version!"

