name: pull-requests
on: pull_request

jobs:
  # This job handles Buf integration. Namely, it provides inline comments
  # for lint issues and breaking changes.
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.24.0"
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/fixie-ai/fixie-proto.git#branch=main"
  # This job adds suggestions for format changes and a Python version increment.
  # Some version increment is necessary for successfully pushing to PyPI, but it's
  # up to developers whether that push should happen.
  format-and-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.24.0"
          github_token: ${{ github.token }}
        # Unlike lint and breaking, format does not make its own suggestions,
        # so we use action-suggester to make them.
      - run: buf format
      - uses: reviewdog/action-suggester@v1
        with:
          tool_name: "buf format"

        # For version increments, things get more tricky because GitHub doesn't
        # allow adding suggestions (or even comments) to a file that isn't yet
        # modified by the PR.
      - uses: tj-actions/changed-files@v37
        id: changed-files
        with:
          files: |
            **/pyproject.toml
      - uses: actions/setup-python@v2
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          python-version: '3.9'
      - uses: snok/install-poetry@v1.3.1
        if: steps.changed-files.outputs.any_changed == 'true'
      - uses: abatilo/actions-poetry@v2
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          poetry-version: 1.2.1
      - run: poetry version patch
        if: steps.changed-files.outputs.any_changed == 'true'
      - uses: reviewdog/action-suggester@v1
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          tool_name: "version bump"
      - uses: thollander/actions-comment-pull-request@v2
        if: steps.changed-files.outputs.any_changed != 'true'
        with:
          message: "If your change should be published to PyPI, don't forget to bump the version!"

