name: pull-requests
on: pull_request

jobs:
  # This job handles Buf integration. Namely, it provides inline comments
  # for lint issues and breaking changes.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.24.0"
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          against: "https://github.com/fixie-ai/fixie-proto.git#branch=main"
