name: push-bsr
on: push
jobs:
  # This job pushes the module to BSR. It creates a draft for most
  # branches and a release for the main branch.
  push-module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: bufbuild/buf-setup-action@v1
        with:
          version: "1.24.0"
          github_token: ${{ github.token }}
      - uses: bufbuild/buf-lint-action@v1
      - uses: bufbuild/buf-breaking-action@v1
        with:
          # For pushes to main, compare against the previous commit.
          against: ${{ github.ref_name == 'main' && 'https://github.com/fixie-ai/fixie-proto.git#branch=main,ref=HEAD~1' || 'https://github.com/fixie-ai/fixie-proto.git#branch=main'}}
      - uses: bufbuild/buf-push-action@v1
        with:
          buf_token: ${{ secrets.BUF_TOKEN }}
          draft: ${{ github.ref_name != 'main' }}


